apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp-demo
  name: myapp-demo
  namespace: myapp-rbh
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: myapp-demo
  template:
    metadata:
      labels:
        app: myapp-demo
    spec:
      containers:
        - image: docker.io/zq975684/myapp-demo:SNAPSHOT-$BUILD_NUMBER
          imagePullPolicy: Always
          name: myapp-demo
          env:
            - name: MYSQL_HOST
              value: $MYSQL_HOST
            - name: MYSQL_PORT
              value: $MYSQL_PORT
            - name: MYSQL_USERNAME
              value: $MYSQL_USERNAME
            - name: MYSQL_PASSWORD
              value: $MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              value: $MYSQL_DATABASE    
          ports:
            - containerPort: 8080 
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 2048Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
